### ISSUE TITLE
アプリ一覧のソート

### ISSUE THREAD

**Issue by tarukosu** [HoloLabInc/HoloLensAppManager#10]

**Comment by tarukosu** [comment]
- アプリ名
- 最終更新日

昇順、降順

**Comment by tarukosu** [comment]
ComboBox を使う。
検索テキスト入力の右側に置く

選択肢は
- 更新日（新しい順）
- 更新日（古い順）
- アプリ名（昇順）
- アプリ名（降順）

前回の選択内容を保存しておく。
アプリを終了して、起動した場合、前回の選択内容のままでソートがされている。

初回起動時のデフォルトは更新日（新しい順）

**Comment by cindychen0204** [comment]
https://github.com/HoloLabInc/HoloLensAppManager/pull/13
